export const actions = [
    "Saved Graph",
    "Printed Presentation",
    "Highlighted Image",
    "Next Page Image",
    "Saved Link",
    "Downloaded Pitchdeck",
    "Exited Slide",
    "Next Page Table",
    "Saved Content",
    "Highlighted Table",
    "Zoomed In Annotation",
    "Zoomed Out Graph",
    "Zoomed Out Link",
    "Removed Bookmark Comment",
    "Previous Page Image",
    "Next Page Annotation",
    "Removed Bookmark Table",
    "Previous Page Table",
    "Sent Feedback Image",
    "Shared Pitchdeck",
    "Highlighted Content",
    "Zoomed Out Link",
    "Copied Attachment",
    "Closed Link",
    "Viewed Snippet",
    "Removed Bookmark Attachment",
    "Exited Table",
    "Opened Video",
    "Closed Video",
    "Previous Page Diagram",
    "Highlighted Pitchdeck",
    "Previous Page Slide",
    "Pasted Link",
    "Exited File",
    "Bookmarked Diagram",
    "Viewed Figure",
    "Shared Annotation",
    "Exited Diagram",
    "Viewed File",
    "Pasted Comment",
    "Printed Diagram",
    "Previous Page File",
    "Printed Chart",
    "Printed Snippet",
    "Bookmarked Snippet",
    "Downloaded Image",
    "Exited Annotation",
    "Zoomed Out Section",
    "Sent Feedback File",
    "Printed Comment",
    "Highlighted Page",
    "Zoomed Out Table",
    "Highlighted Comment",
    "Closed Chart",
    "Sent Annotation",
    "Saved Image",
    "Sent Feedback Video",
    "Copied File",
    "Bookmarked Snippet",
    "Closed Video",
    "Shared File",
    "Next Page Pitchdeck",
    "Next Page Diagram",
    "Next Page Video",
    "Zoomed Out Section",
    "Highlighted Content",
    "Commented Attachment",
    "Removed Bookmark Diagram",
    "Viewed Section",
    "Zoomed Out Annotation",
    "Zoomed Out Chart",
    "Opened Slide",
    "Highlighted Figure",
    "Zoomed In Comment",
    "Next Page Attachment",
    "Previous Page Annotation",
    "Commented Page",
    "Downloaded Section",
    "Previous Page Annotation",
    "Viewed Snippet",
    "Sent Section",
    "Commented Attachment",
    "Opened File",
    "Commented Attachment",
    "Zoomed In Attachment",
    "Copied Table",
    "Sent Feedback Presentation",
    "Shared Video",
    "Copied Section",
    "Sent Feedback Image",
    "Opened Image",
    "Zoomed In Slide",
    "Next Page Figure",
    "Sent Snippet",
    "Sent Chart",
    "Next Page Link",
    "Bookmarked Annotation",
    "Saved Presentation",
    "Printed Snippet",
    "Sent Chart"
];

export const visitors = [
    "Kwesi", "Zuberi", "Kwesi", "Amina", "Moyo", "Akua", "Moyo", "Oba", "Ngozi", "Efe",
    "Amara", "Nkechi", "Oba", "Fatou", "Akua", "Tunde", "Chinwe", "Kelechi", "Femi", "Sekou",
    "Chinwe", "Kwesi", "Omari", "Bayo", "Kofi", "Obinna", "Nia", "Ade", "Esi", "Yemi",
    "Zainab", "Kwesi", "Imani", "Zuberi", "Penda", "Imani", "Moyo", "Zuberi", "Zola", "Gbenga",
    "Imani", "Efe", "Gbenga", "Sade", "Zainab", "Zola", "Amina", "Fatou", "Ngozi", "Chike",
    "Taye", "Nia", "Malik", "Kelechi", "Chinwe", "Gbenga", "Yemi", "Zainab", "Bayo", "Ayo",
    "Nia", "Lamine", "Imani", "Kofi", "Ngozi", "Obinna", "Nia", "Gbenga", "Gbenga", "Zola",
    "Efe", "Lamine", "Juma", "Efe", "Amara", "Moyo", "Amara", "Obinna", "Lamine", "Omari",
    "Zola", "Omari", "Akua", "Ade", "Zuberi", "Malik", "Zola", "Nkechi", "Juma", "Obinna",
    "Fatou", "Ngozi", "Gbenga", "Ade", "Penda", "Nia", "Omari", "Obinna", "Zainab", "Amina"
];